const EMAIL_VERIFICATION_EXPIRY_MS = 15 * 60 * 1000;
const UNVERIFIED_ACCOUNT_RETENTION_MS = 2 * 24 * 60 * 60 * 1000;
module.exports = {
  EMAIL_VERIFICATION_EXPIRY_MS,
  UNVERIFIED_ACCOUNT_RETENTION_MS,
};
